### ISSUE TITLE
RNA tutorial feedback

### ISSUE THREAD

**Issue by nsheff** [databio/example-projects#1]
- make your titles tell the user what they are going to do. instead of "Geofetch", what about "Download raw data from GEO". I would also organize it in "steps" (by numbering them).
- the introduction needs to tell the goal of what you're doing "from raw data to differential expression", right now this is not clear. uninitiated user does not know what 'looper' or 'deseq packager' are, these terms should be introduced and not used in the intro.
- add deseq packager and rna seq pipeline to your prerequisites list. I would also put code for how to at least install or clone each of these (1 line per prereq).

**Comment by nsheff** [comment]
Here is some more feedback for you:

Pretend you are a new user, and go through your tutorial. You will find many things that do not make sense, because you are assuming the user knows lots of knowledge specific to our lab. Here are some examples:
- This is confusing: "make sure your prefetch variable is configured correctly, as described in the geofetch README!"
- you need to describe the environment variables; they are not introduced. what are they for?
- "And then add this section right after the implied_columns section." What is the `-D:null` added for? This is never explained. Actually, none of this explained.
- The introduction still needs to be a little more..."introductive"

- instead of describing what to do in text, actually do it in code. like "Go into the $SRAMETA directory " should accompany the command `cd $SRAMETA`, which is currently left out. The goal is that the code, when executed *without any of the text*, should run. Right now, it wouldn't.
- Never use 'here' as link anchor text, as in "More info can be found here.". always use descriptive link anchor text.
- "add another derived column to the yaml" -> which yaml?

We need to try to eliminate the manual parts:
- "In the sample annotation sheet file, the entries in the protocol column have to be changed to the correct RNA sequencing protocol, which is rnaKallisto for this example." -> how should we eliminate this? Update the pipeline to accept the protocol that's already there? that's what I suggest.
- "Now we will specify the pipeline arguments for rnaKallisto in the project config file. First, add the location of the rnapipe pipeline_interface:" -> can we make this an argument passed to `geofetch` so it can be done in that command, and not manually by the user? or something else?

**Comment by nsheff** [comment]
Also just a small thing: you're inconsistent in use of `backticks` to identify software in-line. For example, you use both `rnaKallisto` and rnaKallisto. I suggest going through and backticking all the software, it just makes it a bit easier to read.

**Comment by stolarczyk** [comment]
**tutorial feedback:**
* instead of just "yaml" I would refer to the file "config_file.yaml" and instead of "csv" - "sample_annotation.csv". Being explicit won't hurt nobody
* provide a link to the repository with the `rivanna4` module and `DESeq` package when you mention it. 
* in 3. when you instruct the user to add a derived column provide a link: https://pepkit.github.io/docs/derived_attributes/ or http://code.databio.org/pepr/articles/feature3_derivedAttributes.html
* change derived_columns to derived_attributes (the name changed, yet it is backwards compatible)
* in the second to last code block use `setwd()` to change the path as you say you're in `R` environment already
* similarly to what @nsheff wrote above - make the names formatting consistent. Not only the `backticks`are inconsistent but also the capitalization. See: `Looper` - `looper`, `DESeq-Packager` - DESeq-Packager - **DESeq-Packager**, $PROCESSED  - `$PROCESSED/GSE107655`

**code feedback:**
* couldn't run `cd $SRAMETA; looper run GSE107655_config.yaml --sp sra_convert --lump 10` it looks like there is no `GSE107655_config.yaml` in the current working directory. It is in `./GSE107655`

**Comment by nsheff** [comment]
@aaron-gu can you comment/close this issue if complete?
